name: Black linter

on:
  pull_request:
    branches:
      - main

jobs:
  pylint:
    if: github.event.pull_request.draft == false
    runs-on: cytopia/black
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: Check codestyle
      run: |
        black --check $(git ls-files '*.py')
