name: MyPy static type check

on:
  pull_request:
    branches:
      - main

jobs:
  mypy:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    container:
      image: airdock/python-poetry
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Static type check
      run: |
        python3 -m pip install mypy
        poetry install
        mypy $(find . -name '*.py')
